### ISSUE TITLE
Command line query returns sometime false TZ

### ISSUE THREAD

**Issue by cnaslain** [judy2k/tzgeo#3]
Hi,

Just try tzgeo which seems really good and easy to use (for me thru a bash command line). Example: `python /usr/lib/python2.6/site-packages/tzgeo -55 -68`

I test several lat,lon points to ensure the results were correct but I found some errors; could you check and feedback me?

Examples of lat,lon points:
48,2.25 => Europe/Paris: OK
21.45, -158.19 => Pacific/Honolulu: OK
-55,-68 => America/Santiago: OK
...
1,10 => Africa/Malabo (guinée): KO -> Should be Africa/Libreville (Gabon)
-1,32 => Africa/Kampala (Ouganda): KO -> Should be AfricaAfrica/Dar_es_Salaam (Tanzanie)
-19,41 => Pacific/Fiji (which is in the middle of the Mozambic channel) -> Should be None ?
-51,72 => Pacific/Auckland (near Heard Island and McDonald Islands) -> Should be None ?

Maybe it does concerns some areas not covered?

Chris

**Comment by judy2k** [comment]
Hi @cnaslain - thanks for raising the issue. I think this is probably the same as #2 - but I'll check. If you're actually using this library then you've given me motivation to fix it :)

**Comment by judy2k** [comment]
... also I can use your specific issues as test cases to make sure I've fixed the issue 👍

**Comment by cnaslain** [comment]
Hi @judy2k.

Yes of course; feel free to use these points to add some test cases. I'm not sure the problem comes from your code; maybe it's a dataset (Where On Earth data) problem?

To validate the initial list of points; I've used the Google Timezone API:
Doc: https://developers.google.com/maps/documentation/timezone/intro  (where in the following URLs the timestamp is the Unix timestamp).
Examples: 
- Gabon: https://maps.googleapis.com/maps/api/timezone/json?location=1,10&timestamp=1476381067
- Mozambic: https://maps.googleapis.com/maps/api/timezone/json?location=-19,41&timestamp=1476381067
- etc.

I was looking for a local solution to request TZ from a GPS location cos I have a large amount of points to process and Google only allows 2.500 req/day.

**Comment by judy2k** [comment]
Hey @cnaslain !

I've (locally) improved the accuracy of the query. 

1, 10 is an interesting one - it's *right* on the border between Guinée and Gabon. With the Google API, a latitude of 1.0001 returns Libreville, and 1.0002 returns Malabo. I'm probably going to leave this as a rounding error!

I have a few more queries to check, and then I'll make a new release, probably this evening.

**Comment by judy2k** [comment]
This is resolved in v0.0.4, barring some border inaccuracy issues which are out of my control!
