### ISSUE TITLE
Syntax Error on Pip install

### ISSUE THREAD

**Issue by tjdodson** [judy2k/tzgeo#6]
`pip install tzgeo
Collecting tzgeo
  Downloading https://files.pythonhosted.org/packages/6a/74/0b0d2316be7ded5fa3f9ee8b2b77da5c2c2b72543903d29fe2ba615d0513/tzgeo-0.0.4-py2.py3-none-any.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 2.4MB/s 
Collecting pyspatialite>=3.0.1-alpha-0 (from tzgeo)
  Downloading https://files.pythonhosted.org/packages/cc/2a/ffb126f3e8890ab0da951a83906e54528a13ce4b913303dea8bed904e160/pyspatialite-3.0.1-alpha-0.tar.gz (2.6MB)
    100% |████████████████████████████████| 2.6MB 6.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7y/t9hdbkl96fd8zf05x4ddphzwzv961n/T/pip-install-e2urtecs/pyspatialite/setup.py", line 66
        print "Is sphinx installed? If not, try 'sudo easy_install sphinx'."
                                                                           ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Is sphinx installed? If not, try 'sudo easy_install sphinx'.")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7y/t9hdbkl96fd8zf05x4ddphzwzv961n/T/pip-install-e2urtecs/pyspatialite/`

**Comment by judy2k** [comment]
It looks like you're using Python 3 (GREAT!) but this, very undermaintained, library was written for Python 2, and hasn't been ported yet, unfortunately.
